from django.db import models
# using inspectdb worldcities autogenerated a model!


class Worldcities(models.Model):
    city = models.TextField(blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)
    lng = models.FloatField(blank=True, null=True)
    country = models.TextField(blank=True, null=True)
    id = models.IntegerField(blank=True, primary_key=True)
    # make ID the one primary
    class Meta:
        managed = False
        db_table = 'worldcities'